#!/usr/bin/env python3
"""Generate the wiki's reference pages from the objects that already know.

Three pages describe things the code defines exactly once, and a hand-written
copy of any of them would be wrong within a month:

    Configuration.md   every field of every config model, from config.schema()
    Tools.md           the four mirror tools, from a live server's tool list
    Endpoints.md       the HTTP surface, from spec.build_spec()

They are built in-process, from the installed package, rather than read off
disk. ``openapi.yaml`` is a generated artifact and is not committed, so
depending on the file would mean this script could only run after another one
had written it -- and could render a wiki from a stale copy if it had not.

What is NOT generated is the prose. Every page ends by including a hand-written
fragment from ``wiki/notes/<page>.notes.md`` when one exists, so guidance a
schema cannot express has somewhere to live that regeneration will not flatten.
The guides beside these pages -- Home, Installing, Deployment, Sources, Skills,
Prompts, Scoping, Operations -- are hand-written in full and this script never
touches them.

    python scripts/generate_wiki.py            # write the pages
    python scripts/generate_wiki.py --check    # fail if they are out of date
"""

from __future__ import annotations

import argparse
import asyncio
import json
import pathlib
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from kubed.mcp_kb import config as config_module  # noqa: E402
from kubed.mcp_kb.config import Config, schema  # noqa: E402
from kubed.mcp_kb.mcp import prompts as prompts_module  # noqa: E402
from kubed.mcp_kb.mcp import request as request_module  # noqa: E402
from kubed.mcp_kb.mcp import tools as tools_module  # noqa: E402
from kubed.mcp_kb.server import KnowledgeBase  # noqa: E402
from kubed.mcp_kb.spec import build_spec  # noqa: E402

WIKI = REPO / "wiki"
NOTES = WIKI / "notes"
# `<page>.notes.md`, not `<page>.md`, and the suffix is load-bearing. A GitHub
# wiki addresses a page by BASENAME whatever directory it sits in, so a note
# named for its page would answer to the same URL as the page it belongs to --
# and GitHub serves the fragment, leaving the page looking like it had lost
# everything but its prose while the file on disk was perfect. The suffix is
# what keeps the two apart; test_no_page_is_shadowed_by_a_file_in_a_subdirectory
# fails if it is ever dropped.
NOTES_SUFFIX = ".notes.md"

BANNER = (
    "<!-- Generated by scripts/generate_wiki.py from {source}. Do not edit:\n"
    "     prose belongs in wiki/notes/{name}.notes.md, which is included below. -->"
)

SEPARATOR = "\n\n"

FOOTER_LINKS = "[Home](Home) · [Installing](Installing) · [Deployment](Deployment)"

# The config models, in the order a reader meets them: the file itself, then
# what it declares, then the three source kinds, then the two small things a
# source points at. `Config` is the schema's root; the rest are its `$defs`.
MODELS = [
    "Config",
    "Library",
    "Include",
    "FileSource",
    "GitSource",
    "WebdavSource",
    "BasicAuth",
    "EnvRef",
]


# -- rendering helpers ---------------------------------------------------------


def clean(text: str | None) -> str:
    """Collapse a docstring's hard wrapping into flowing markdown.

    Docstrings here are reStructuredText-flavoured, so the double backticks and
    the ``::`` that opens a literal block are translated on the way out rather
    than left for a reader to decode.
    """
    if not text:
        return ""
    text = text.replace("``", "`").replace("::\n", ":\n").replace("--", "—")
    out = []
    for block in text.split("\n\n"):
        stripped = block.strip("\n")
        # A code block or a list keeps its line breaks; prose does not.
        if stripped.lstrip().startswith(("- ", "* ", "|", "```", "    ")):
            out.append(stripped)
        else:
            out.append(" ".join(line.strip() for line in stripped.splitlines()))
    return "\n\n".join(b for b in out if b)


def cell(text: str) -> str:
    """One table cell: a pipe would end it, and a newline would end the row."""
    return " ".join(text.split()).replace("|", "\\|")


def table(rows: list[list[str]], head: list[str]) -> str:
    lines = ["| " + " | ".join(head) + " |", "|" + "|".join(["---"] * len(head)) + "|"]
    lines += ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


# Header names arrive lowercased from the constants that define them, and
# `.title()` alone would print `X-Mcp-Resources` for a header spelt `X-MCP-`.
ACRONYMS = {"mcp"}


def header_name(lowercase: str) -> str:
    """One of request.py's header constants, in the casing it is written in."""
    parts = lowercase.split("-")
    return "-".join(p.upper() if p in ACRONYMS else p.title() for p in parts)


def anchor(name: str) -> str:
    """A GitHub heading anchor for a model's section on the same page."""
    return "#" + name.lower()


def ref_name(node: dict) -> str:
    return node["$ref"].rsplit("/", 1)[-1]


def type_of(field: dict, link: bool = False) -> str:
    """A field's type, with the null branch read as optionality instead.

    ``anyOf: [string, null]`` is how an optional field arrives from a pydantic
    schema, and printing it verbatim would tell a reader about JSON Schema
    rather than about the setting they are trying to write.
    """
    branches = field.get("anyOf") or field.get("oneOf")
    if branches:
        names = [
            type_of(b, link) for b in branches if b.get("type") != "null" or len(b) > 1
        ]
        return " or ".join(n for n in names if n) or "any"
    if "$ref" in field:
        name = ref_name(field)
        return f"[{name}]({anchor(name)})" if link else name
    values = field.get("additionalProperties")
    if isinstance(values, dict) and values:
        return f"object of {type_of(values, link)}"
    declared = field.get("type")
    if isinstance(declared, list):
        names = [n for n in declared if n != "null"]
        return " or ".join(names) or "any"
    if declared == "array":
        items = field.get("items") or {}
        inner = type_of(items, link) if items else "any"
        return f"list of {inner}"
    return declared or "any"


def default_of(field: dict) -> str:
    """The default as YAML would take it, or an em dash when there is none.

    A model-valued default arrives as that model with every field at ``None``
    -- which is what omitting it from the file already means -- so the nulls
    are dropped and what is left is the shape you would actually write.
    """
    if "default" not in field:
        return "—"
    value = field["default"]
    if value is None:
        return "—"
    if isinstance(value, dict):
        value = {k: v for k, v in value.items() if v is not None}
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, str):
        return f'`"{value}"`' if value == "" else f"`{value}`"
    return f"`{json.dumps(value, separators=(', ', ': '))}`"


def notes_of(field: dict) -> str:
    """What the schema constrains this field to, beyond its type.

    pydantic carries no per-field descriptions in this config model — the prose
    is in each model's docstring, printed above its table — so the column would
    be empty. The constraints are the part a table can say better than prose:
    a `refresh` pattern and a `cache` enum are exactly what someone writing the
    file gets wrong.
    """
    described = clean(field.get("description"))
    parts = [described] if described else []
    for branch in [field, *(field.get("anyOf") or [])]:
        if "enum" in branch:
            parts.append("one of " + ", ".join(f"`{v}`" for v in branch["enum"]))
        if "pattern" in branch:
            parts.append(f"matches `{branch['pattern']}`")
    return ". ".join(parts)


def fields(model: dict) -> str:
    props = model.get("properties") or {}
    if not props:
        return "_No fields._"
    required = set(model.get("required") or [])
    rows = []
    for name, field in props.items():
        mark = "**yes**" if name in required else "no"
        rows.append(
            [
                f"`{name}`",
                type_of(field, link=True),
                mark,
                default_of(field),
                notes_of(field),
            ]
        )
    head = ["Field", "Type", "Required", "Default", "Notes"]
    if not any(row[-1] for row in rows):
        return table([row[:-1] for row in rows], head[:-1])
    return table(rows, head)


def section(name: str, description: str, body: str) -> str:
    """One `## Name` section, without a hole where a missing description was."""
    return SEPARATOR.join(part for part in (f"## {name}", description, body) if part)


def note_for(page: str) -> str:
    note = NOTES / f"{page}{NOTES_SUFFIX}"
    return f"\n\n{note.read_text().strip()}\n" if note.is_file() else ""


# -- Configuration -------------------------------------------------------------


def configuration_page() -> str:
    """Every config model, from `Config.model_json_schema()`."""
    root = schema()
    defs = root.get("$defs", {})
    sections = []
    for name in MODELS:
        model = root if name == "Config" else defs[name]
        description = clean(model.get("description"))
        sections.append(section(name, description, fields(model)))

    missing = sorted(set(defs) - set(MODELS))
    if missing:
        raise SystemExit(f"add these to MODELS in {__file__}: {', '.join(missing)}")

    schemes = table(
        [[f"`{scheme}://`", f"[{kind}]({anchor(kind)})"] for scheme, kind in _kinds()],
        ["URL scheme", "Source kind"],
    )

    body = SEPARATOR.join(sections)
    return f"""{BANNER.format(source="config.schema()", name="Configuration")}

# Configuration

The config file says **what** to serve. Environment variables and flags say
**how** to run — transport, port, cache directory — and the two never overlap;
those are in [Deployment](Deployment). A key this page does not list is an
error rather than a value quietly ignored, because a config that serves nothing
is the worst failure a config file has.

`mcp-kb schema` prints this as JSON Schema, and `config.schema.json` in the
repository is the same document, so an editor with
`# yaml-language-server: $schema=…` at the top of the file completes and
validates as you type.

For what each source kind does with these fields, see [Sources](Sources).

## URL scheme → source kind

The `url` decides which model a source is validated against. There is no
`kind:` field to set and no way to override it.

{schemes}

{body}
{note_for("Configuration")}
---

{FOOTER_LINKS} · [Sources](Sources)
"""


def _kinds() -> list[tuple[str, str]]:
    """(scheme, model name) per `config.SCHEMES`, in the order it declares them."""
    models = {"file": "FileSource", "git": "GitSource", "webdav": "WebdavSource"}
    return [(scheme, models[tag]) for scheme, tag in config_module.SCHEMES.items()]


# -- Tools ---------------------------------------------------------------------


def _live_tools() -> list:
    """The tool list of a real server, built over a throwaway `file://` source.

    A tool's schema is assembled by FastMCP from the registered functions and
    the prompt transform, so the only way to describe the four accurately is to
    stand a server up and ask it. The source is one skill in a temporary
    directory: enough for the server to boot, and nothing that reaches a tool
    schema, which is the same for an empty catalogue and a full one.
    """
    with tempfile.TemporaryDirectory() as raw:
        tmp = pathlib.Path(raw)
        skill = tmp / "library" / "skills" / "example"
        skill.mkdir(parents=True)
        (skill / "SKILL.md").write_text(
            "---\nname: example\ndescription: An example skill.\n---\n\nBody.\n"
        )
        config = Config.model_validate(
            {"sources": [{"name": "example", "url": f"file://{tmp / 'library'}"}]}
        )
        server = KnowledgeBase(config, tmp / "cache")
        found = asyncio.run(server.mcp.list_tools(run_middleware=False))
        return [tool.to_mcp_tool() for tool in found]


def _reveals() -> dict[str, tuple[str, str, str]]:
    """Tool name -> (the pair's title, its URL parameter, its header).

    Read from the modules that own each set rather than written out here, so a
    tool that joins one of the pairs is described by this page without the page
    being edited.
    """
    resources = (
        "Resource mirror",
        request_module.RESOURCES_PARAM,
        request_module.RESOURCES_HEADER,
    )
    prompts = (
        "Prompt mirror",
        request_module.PROMPTS_PARAM,
        request_module.PROMPTS_HEADER,
    )
    pairs = dict.fromkeys(sorted(tools_module.MIRROR_TOOLS), resources)
    pairs.update(dict.fromkeys(sorted(prompts_module.PROMPT_TOOLS), prompts))
    return pairs


def _arguments(tool) -> str:
    inputs = tool.input_schema or {}
    props = inputs.get("properties") or {}
    if not props:
        return "_Takes no arguments._"
    required = set(inputs.get("required") or [])
    rows = [
        [
            f"`{name}`",
            type_of(field),
            "**yes**" if name in required else "no",
            default_of(field),
            clean(field.get("description")),
        ]
        for name, field in props.items()
    ]
    return table(rows, ["Argument", "Type", "Required", "Default", "Notes"])


def _annotations(tool) -> str:
    hints = tool.annotations
    if hints is None:
        return "_None._"
    rows = [
        [f"`{name}`", f"`{str(value).lower()}`" if isinstance(value, bool) else value]
        for name, value in hints.model_dump(exclude_none=True).items()
    ]
    return table(rows, ["Annotation", "Value"])


def tools_page() -> str:
    """The four mirror tools, from a live server's `list_tools`."""
    reveals = _reveals()
    found = _live_tools()
    unknown = sorted(t.name for t in found if t.name not in reveals)
    if unknown:
        raise SystemExit(f"tool with no mirror pair: {', '.join(unknown)}")

    summary = table(
        [
            [
                f"[`{tool.name}`](#{tool.name})",
                reveals[tool.name][0],
                f"`?{reveals[tool.name][1]}=off`",
                f"`{header_name(reveals[tool.name][2])}: off`",
            ]
            for tool in found
        ],
        ["Tool", "Mirrors", "Shown by", "or by header"],
    )

    sections = []
    for tool in found:
        _, param, header = reveals[tool.name]
        sections.append(
            f"""## `{tool.name}`

{clean(tool.description)}

Listed only for a client that sent `?{param}=off` or `{header_name(header)}: off`.
It is callable either way — hiding a tool from a listing is a presentation
choice, not a refusal to run it.

### Arguments

{_arguments(tool)}

### Annotations

{_annotations(tool)}"""
        )

    body = SEPARATOR.join(sections)
    return f"""{BANNER.format(source="a live server's tool list", name="Tools")}

# Tools

Every tool this server has is a **mirror**. The catalogue is MCP resources and
MCP prompts; these four exist for the clients that implement neither, to which a
resource-only server looks empty. n8n's MCP Client Tool is the one that made
them necessary.

Each pair is revealed separately, because a client may have one feature and not
the other. A client says so on the MCP URL, or in a header that beats the URL:

```
http://mcp-kb.flow.svc.cluster.local:8000/mcp?resources=off&prompts=off
```

{summary}

The vocabulary is deliberately the protocol's own — list addresses, read an
address — so an agent that can drive MCP resources can drive these with nothing
new to learn. See [Installing](Installing) for where each client wants that URL,
and [Skills](Skills) for the `skill://` grammar `read_resource` takes.

{body}
{note_for("Tools")}
---

{FOOTER_LINKS} · [Scoping](Scoping)
"""


# -- Endpoints -----------------------------------------------------------------


def _resolve(spec: dict, node: dict) -> dict:
    """A schema with its local `$ref` followed and its `allOf` branches merged."""
    if "$ref" in node:
        return _resolve(spec, spec["components"]["schemas"][ref_name(node)])
    if "allOf" in node:
        merged: dict = {"type": "object", "properties": {}, "required": []}
        for branch in node["allOf"]:
            part = _resolve(spec, branch)
            merged["properties"].update(part.get("properties") or {})
            merged["required"] += part.get("required") or []
        return merged
    return node


def _schema_fields(spec: dict, model: dict) -> str:
    props = model.get("properties") or {}
    extra = model.get("additionalProperties")
    if not props and isinstance(extra, dict):
        name = type_of(extra, link=True)
        return f"An object keyed by name, each value a {name}."
    if not props:
        return "_An object._"
    required = set(model.get("required") or [])
    rows = []
    for name, field in props.items():
        # A `const` is the type: `status` is the string "ok", not "a string".
        fixed = field.get("const")
        kind = f"`{fixed}`" if fixed is not None else type_of(field, link=True)
        mark = "**yes**" if name in required else "no"
        rows.append([f"`{name}`", kind, mark, clean(field.get("description"))])
    return table(rows, ["Field", "Type", "Always", "Means"])


def endpoints_page() -> str:
    """The HTTP surface, from the OpenAPI document `routes.py` serves."""
    spec = build_spec()

    servers = table(
        [[f"`{s['url']}`", clean(s.get("description"))] for s in spec["servers"]],
        ["URL", "Is"],
    )

    operations = []
    for path, item in spec["paths"].items():
        for method, op in item.items():
            responses = table(
                [
                    [
                        f"`{code}`",
                        type_of(
                            body["content"]["application/json"]["schema"], link=True
                        ),
                        clean(body.get("description")),
                    ]
                    for code, body in sorted(op["responses"].items())
                ],
                ["Status", "Body", "Means"],
            )
            verb = "" if method == "get" else "-X POST "
            operations.append(
                f"""## `{method.upper()} {path}`

> {clean(op.get("summary"))}

{clean(op.get("description"))}

```bash
curl {verb}$MCP_KB{path}
```

{responses}"""
            )

    schemas = [
        section(
            name,
            clean(_resolve(spec, body).get("description")),
            _schema_fields(spec, _resolve(spec, body)),
        )
        for name, body in spec["components"]["schemas"].items()
    ]

    body = SEPARATOR.join(operations)
    models = SEPARATOR.join(schemas)
    version = spec["openapi"]
    return f"""{BANNER.format(source="spec.build_spec()", name="Endpoints")}

# Endpoints

Two plain HTTP routes sit beside the MCP transport at `/mcp`, outside the
protocol on purpose: checking whether a pod is serving what it should needs
curl, not an MCP client. A third serves this document.

Nothing here is authenticated. There is no auth on this server at all — every
skill it serves is public markdown — so there is no credential to gate a
description of it behind. What that means operationally is in
[Operations](Operations).

| Route | Does |
|---|---|
| `GET /health` | what this pod is serving, and which sources loaded |
| `POST /reindex` | rebuild every source now |
| `GET /openapi.yaml` | this surface as OpenAPI {version}, built per process |

## Servers

{servers}

{body}

# Schemas

{models}
{note_for("Endpoints")}
---

{FOOTER_LINKS} · [Operations](Operations)
"""


# -- driver --------------------------------------------------------------------


def pages() -> dict[str, str]:
    return {
        "Configuration.md": configuration_page(),
        "Tools.md": tools_page(),
        "Endpoints.md": endpoints_page(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if stale")
    args = parser.parse_args()

    if not WIKI.is_dir():
        raise SystemExit("wiki/ is not checked out — run: git submodule update --init")

    rendered = pages()
    stale = []
    for name, body in rendered.items():
        target = WIKI / name
        if not target.is_file() or target.read_text() != body:
            stale.append(name)
        if not args.check:
            target.write_text(body)

    if args.check:
        if stale:
            print("stale wiki pages: " + ", ".join(stale), file=sys.stderr)
            print("run python scripts/generate_wiki.py", file=sys.stderr)
            return 1
        print(f"{len(rendered)} wiki pages up to date")
        return 0

    print(f"wrote {len(rendered)} pages to {WIKI}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
